version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.1.0

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: build
          command: yarn

      - run:
          name: unit tests
          command: yarn test:server
