version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.18.1

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: build
          command: yarn

      - run:
          name: unit tests
          command: yarn test:server
